feat: check ctype hash and trusted attester list
KILTprotocol/web3-login-demo pull request #36
Opened 2023-08-16 13:11 UTC by Dudleyneedham

## fixes NO TICKET

Adds the latest SKYC Email CType.

This checks the attester of the credential against the list of ctypes and the corresponding ctype.

## How to test:
Please provide a brief step-by-step instruction.
If necessary provide information about dependencies (specific configuration, branches, database dumps, etc.)

- Step 1
- Step 2
- etc.

## Checklist:

- [ ] I have verified that the code works
- [ ] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [ ] I have [left the code in a better state](https://deviq.com/principles/boy-scout-rule)
- [ ] I have documented the changes (where applicable)
    * Either PR or Ticket to update [the Docs](https://github.com/KILTprotocol/docs)
    * Link the PR/Ticket here

2023-08-17 07:41 UTC, Dudleyneedham commented on backend/src/credentials/verifySubmittedCredential.ts
>    if (ourTrustedAttesters) {
I think I could kill this line.

2023-08-22 10:02 UTC, kilted-andres requested changes

2023-08-22 10:02 UTC, kilted-andres commented on backend/src/credentials/verifySubmittedCredential.ts
> +  })
```suggestion
    const ourTrustedAttesters = cTypeRequested.cTypes.find((ctype) => {
    ctype.cTypeHash !== credential.claim.cTypeHash
  })?.trustedAttesters
```

2023-08-22 10:02 UTC, kilted-andres commented on backend/src/credentials/verifySubmittedCredential.ts
> +    if (!ourTrustedAttesters) {
```suggestion
  if (ourTrustedAttesters?.includes(attesterOfTheirCredential)) {
```

2023-08-22 10:02 UTC, kilted-andres commented on backend/src/credentials/listOfRequests.ts
> +      requiredProperties: ['Email']
nice

2023-10-04 15:24 UTC, kilted-andres approved these changes
Great!

2023-10-06 12:24 UTC, merged